/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#8B6D31',
        'primary-dark': '#6B5426',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container': '#212020',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-variant': '#353534',
        'on-surface': '#e6e1e1',
        'on-surface-variant': '#cac4c4',
        background: '#131313',
        'on-background': '#e5e2e1',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Primary palette
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'on-primary': '#3c2f00',
        'primary-container': '#8B6D31',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        'surface-tint': '#e9c349',
        // Secondary (red accent)
        secondary: '#ffb3ad',
        'secondary-container': '#b60319',
        'on-secondary': '#680009',
        'on-secondary-container': '#ffc2bd',
        'on-secondary-fixed': '#410003',
        'on-secondary-fixed-variant': '#930011',
        'secondary-fixed': '#ffdad6',
        'secondary-fixed-dim': '#ffb3ad',
        // Tertiary
        tertiary: '#bfcdff',
        'tertiary-container': '#97b0ff',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-tertiary': '#082b72',
        'on-tertiary-container': '#254188',
        'on-tertiary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#27438a',
        // Other
        outline: '#99907c',
        'outline-variant': '#4d4635',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      fontFamily: {
        sans: ['Open Sans', 'sans-serif'],
        display: ['Montserrat', 'sans-serif'],
        condensed: ['Oswald', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'label-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Open Sans', 'sans-serif'],
        'body-lg': ['Open Sans', 'sans-serif'],
        caption: ['Open Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '800' }],
        'label-md': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        md: '24px',
        lg: '48px',
        'margin-mobile': '20px',
        gutter: '24px',
        'margin-desktop': '64px',
        xs: '4px',
        xl: '80px',
        sm: '12px',
        base: '8px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: {
        marquee: 'marquee 40s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
